gestio_aules/app/__init__.py
from flask import Flask, Blueprint, render_template, redirect, request, flash, url_for, g, send_from_directory
import requests, os, json
#from flask_login import current_user

from functools import wraps
app = Flask(__name__)
app.secret_key = "gfrefiwbuocfr6g1456841/gtr46tr/*gtr/gtr39g4"

@app.route('/internet/static/<path:path>')
def my_static(path):
	return send_from_directory(os.path.join(app.root_path, 'static'), path)

from .config.config import readConfig
c=readConfig()
app.cfg=c.getConfig()

from .auth.Users import auth
au=auth()

bpWork = Blueprint('bpWork',__name__)

@bpWork.before_request
def profe_auth():
	devel_user=au.addDevelUser()
	g.user=devel_user
	if not g.user['role'] == 'profe' and not g.user['role'] == 'admin':
		return render_template('pages/errorValidacio.html')
	return

bpAdmin = Blueprint('bpAdmin', __name__)

@bpAdmin.before_request
def admin_auth():
	devel_user=au.addDevelUser()
	g.user=devel_user
	if not g.user['role'] == 'admin':
		return render_template('pages/noAdmin.html')
	return

from .views import admin, landing, aula_desconeguda, about, errors, logout

app.register_blueprint(bpWork, url_prefix='/internet')
app.register_blueprint(bpAdmin, url_prefix='/internet/admin')

gestio_aules/app/views/about.py
from flask import render_template
from app import app

@app.route('/about', methods=['GET'])
def about():
    return render_template('pages/about.html')

gestio_aules/app/views/admin.py
from flask import render_template, request, g, url_for, redirect
import json, requests, re
from app import app, bpAdmin

@bpAdmin.route('/', methods=['GET'])
def admin():
    r = requests.get('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin')
    dades = json.loads(r.text)
    dies = [{'key':'mon','value':'Dilluns'},{'key':'tue','value':'Dimarts'},{'key':'wed','value':'Dimecres'},{'key':'thu','value':'Dijous'},{'key':'fri','value':'Divendres'}]
    return render_template('pages/admin.html',dades=dades, dies=dies, user=g.user)

@bpAdmin.route('/add_aula/<nom>/<ip>', methods=['POST'])
def add_aula(nom,ip):
    nom = 'aula_' + nom
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin/new_aula/' + nom + '/' + ip)
    if r.status_code == 500:
        if r.text == "The IP of this classroom already exists":
            return "L'ip de l'aula ja existeix",500,{'ContentType':'text/plain'}
        elif r.text == "The clasroom name already exists":
            return "El nom de l'aula ja existeix",500,{'ContentType':'text/plain'}
        return "No s'ha pogut afegir l'aula",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

@bpAdmin.route('/remove_aula/<id>/<aula>', methods=['POST'])
def remove_aula(id,aula):
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin/remove_aula/' + id + '/' + aula)
    if r.status_code == 500:
        return "Could not remove the aula",500,{'ContentType':'text/plain'}
    return "Deleted succesfully",200,{'ContentType':'text/plain'}

@bpAdmin.route('/new_rule/<aula>/<dia>/<interval>', methods=['POST'])
def admin_new_rule(aula,dia,interval):
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin/new_rule/' + aula + '/' + dia + '/' + interval)
    if r.status_code == 500:
        return "Could not add the rule",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

@bpAdmin.route('/remove_rule/<id>/<aula>', methods=['POST'])
def admin_remove_rule(id,aula):
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin/remove_rule/' + id + '/' + aula)
    if r.status_code == 500:
        return "Could not remove the rule",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

@bpAdmin.route('/remove_all', methods=['POST'])
@bpAdmin.route('/remove_all/<aula>', methods=['POST'])
def admin_remove_all(aula=None):
    if aula:
        r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin/remove_all/' + aula)
        if r.status_code == 500:
            return "Could not remove all the rules",500,{'ContentType':'text/plain'}
        return "All rules from the class " + aula + " removed",200,{'ContentType':'text/plain'}
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/admin/remove_all')
    if r.status_code == 500:
        return "Could not remove all the rules",500,{'ContentType':'text/plain'}
    return "All rules removed",200,{'ContentType':'text/plain'}

@bpAdmin.route('/get/drops/<ip>', methods=['GET'])
def get_drops(ip):
    r = requests.get('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/get/drops/' + ip)
    if r.status_code == 500:
        return "Could not get the drops from that class",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

@bpAdmin.route('/get/aulesDT', methods=['GET'])
def aulesDT():
    r = requests.get('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/get/aulesDT')
    if r.status_code == 500:
        return "Could not get the drops from that class",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

gestio_aules/app/views/aula_desconeguda.py
import json
import requests

from flask import render_template, request, url_for, redirect, g
from app import app, bpWork

@bpWork.route('/aula_desconeguda', methods=['GET'])
def aula_desconeguda():
    return redirect(url_for('landing'))

@bpWork.route('/aula_desconeguda/activacio/<aula>', methods=['POST'])
def activacio(aula):
    remote_addr=request.headers['X-Forwarded-For'] if 'X-Forwarded-For' in request.headers else request.remote_addr
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/aula_desconeguda/activacio/' + remote_addr + '/' + g.user['id'] + '/' + aula )
    if r.status_code == 500:
        return "Could not send the email",500,{'ContentType':'text/plain'}
    return "Email succesfully sent",200,{'ContentType':'text/plain'}

gestio_aules/app/views/errors.py
from flask import render_template
from app import app

@app.errorhandler(404)
def not_found(e):
    return render_template('pages/404.html')

gestio_aules/app/views/landing.py
from flask import render_template, request, url_for, redirect, g
import json, requests
from app import app, bpWork

@bpWork.route('/', methods=['GET'])
def landing():
    remote_addr=request.headers['X-Forwarded-For'] if 'X-Forwarded-For' in request.headers else request.remote_addr
    r = requests.get('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/landing/' + remote_addr)
    if r.status_code == 500:
        return render_template('pages/aula_desconeguda.html',user=g.user)
    dades = json.loads(r.text)
    dies = [{'key':'mon','value':'Dilluns'},{'key':'tue','value':'Dimarts'},{'key':'wed','value':'Dimecres'},{'key':'thu','value':'Dijous'},{'key':'fri','value':'Divendres'}]
    return render_template('pages/landing.html', dades=dades,dies=dies, user=g.user)

@bpWork.route('/landing/new_rule/<dia>/<interval>', methods=['POST'])
def new_rule(dia,interval):
    remote_addr=request.headers['X-Forwarded-For'] if 'X-Forwarded-For' in request.headers else request.remote_addr
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/landing/new_rule/' + remote_addr + '/' + dia + '/' + interval)
    if r.status_code == 500:
        return "Could not add the rule",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

@bpWork.route('/landing/remove_rule/<id>', methods=['POST'])
def remove_rule(id):
    remote_addr=request.headers['X-Forwarded-For'] if 'X-Forwarded-For' in request.headers else request.remote_addr
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/landing/remove_rule/' + remote_addr + '/' + id)
    if r.status_code == 500:
        return "Failed to remove the rule",500,{'ContentType':'text/plain'}
    dades = json.loads(r.text)
    return json.dumps(dades),200,{'ContentType':'application/json'}

@bpWork.route('/landing/remove_all', methods=['POST'])
def remove_all():
    remote_addr=request.headers['X-Forwarded-For'] if 'X-Forwarded-For' in request.headers else request.remote_addr
    r = requests.post('http://'+app.cfg['ip_api']+':'+app.cfg['port_api']+'/landing/remove_all/' + remote_addr)
    return "Removed all rules",200,{'ContentType':'text/plain'}

gestio_aules/app/views/logout.py
from app import app
from flask import redirect

@app.route('/internet/logout', methods=['GET'])
def logout():
    return redirect("{}/logout".format(app.cfg['sesman_url']))

gestio_aules/app/templates/pages/about.html
<html>
    <head>
        <META charset="UTF-8">
        <TITLE>Internet</TITLE>
        <link href="/internet/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/internet/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <style>
            .divcentre {
                position: absolute;
                top: 45%;
                left:50%;
                transform: translate(-50%,-50%);
            }
        </style>
    </head>
    <body>
        <div style="margin-top: 1%; margin-left: 1%">
            <a class="btn btn-default btn-lg grey" href="{{url_for('logout')}}">
                <i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>&nbsp;&nbsp;Log Out
            </a>
        </div>
        <div class="row" style=" margin: 0 20px">
          <br>
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="text-align:center;">
                <img src="/internet/static/css/img/ladybug.png" width="110px" height="95px">
            </div>
        </div>
        <br>
        <div class="row" style=" margin: 0 20px">
          <div class="col-sm-2 col-md-2 col-xs-4 col-lg-3">
          </div>
          <div class="col-sm-8 col-md-8 col-xs-4 col-lg-6 jumbotron" style="background-image: url(/css/img/isard.svg); background-size: 100%;">
            <div class="container for-about">
                 <h1>Isard Orchestrator</h1>
                 <p>A platform to orchestrate your virtual desktops.</p>
                 <div class="col-lg-6">
                   <p>Open Source code that will allow you to:</p>
                   <li>Create desktops and get it running in seconds.</li>
                   <li>Start your personal desktop.</li>
                   <li>Share your desktop as a template for other users.</li>
                   <li>Connect your usb devices seamlessly.</li>
                   <li>Incremental disk images which reduces storage.</li>
                   <li>Stand-alone Isard hypervisor/nas storage.</li>
                   <li>Orchestrate multiple Isard hypervisors with scalation.</li>
                   <li>Much more to come!</li>
                </div>
            </div>
          </div>
          <div class="col-sm-2 col-md-2 col-xs-4 col-lg-3">
          </div>
        </div>
        <hr>
        <div class="row" style=" margin: 0 20px">
          <div class="col-sm-2 col-md-2 col-xs-4 col-lg-3">
          </div>
          <div class="col-sm-8 col-md-8 col-xs-4 col-lg-6 text-center">
            <!--
            		<p>info@isard.io</p>
            		<p><i>Licensed under GPL v3 license</i></p>
            -->
            		<h3>Authors:</h3>
            		<b>Alberto Larraz Dalmases</b><br>
                    (alberto.larraz@gmail.com)<br>
            		<b>Josep Maria Viñolas Auquer</b><br>
                    (vinolasbcn@gmail.com)
          </div>
          <div class="col-sm-2 col-md-2 col-xs-4 col-lg-3">
          </div>
        </div>
    </body>
</html>

gestio_aules/app/templates/pages/admin.html
<!DOCTYPE html>
<html lang="en">

    <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />
    
        <title>Internet</title>

		<link href="/internet/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/internet/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <link href="/internet/static/bower_components/bootstrap-select-1.12.4/dist/css/bootstrap-select.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/bootstrap-select-1.12.4/dist/js/bootstrap-select.min.js"></script>
        <script src="/internet/static/bower_components/pnotify/dist/js/pnotify.custom.min.js"></script>
        <link href="/internet/static/bower_components/pnotify/dist/css/pnotify.custom.min.css" rel="stylesheet">
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <link type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
        <style>

            td.details-control {
                background: url('/internet/static/css/img/angle-arrow-down.svg') no-repeat center center;
                background-size: 10%;
                cursor: pointer;
            }

            tr.shown td.details-control {
                background: url('/internet/static/css/img/angle-arrow-up.png') no-repeat center center;
                background-size: 10%;
                cursor: pointer;
            }

            #add {
              display: inline-block;
              padding-left: 30px;
              float: left;
              width:50%;
              text-align: center;
            }

        </style>
        <script src="/internet/static/js/admin.js"></script>
    </head>
    <body>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="margin-top:1%">
            <ul class="nav navbar-nav navbar-right" style="margin-right:2%">
                <li>
                    <button class="btn btn-default btn-lg grey" data-toggle="dropdown" aria-expanded="false">
                        {{ user.name }}&nbsp;&nbsp;<i class="glyphicon glyphicon-th-list"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li>
                            <a href="{{ url_for('bpWork.landing') }}"><i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;Professor</a>
                        </li>
                        <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>&nbsp;&nbsp;Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="text-align:center; margin-top:5%">
            <img src="/internet/static/css/img/ladybug.png" width="110px" height="95px"><br><br>
        </div>
        <h1 style="text-align:center;">Gestió d'aules</h1>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
            <h2 style="text-align:center;">Afegir aula</h2><hr>
                <div style="text-align:center;" class="form-inline">
                    <input id="naula" type="text" class="form-control" placeholder="Nom de l'aula <aula_nom>">
                    <input id="nip" type="text" class="form-control" placeholder="IP"  minlength="7" maxlength="14">
                    <button onclick="add_aula()" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Afegir</button>
                </div>
            <h2 style="text-align:center;">Eliminar aula</h2><hr>
                <div style="text-align:center;">
                    <select value="daules" id="daules" style="text-align:center" class="selectpicker show-tick" data-show-subtext="true" data-live-search="true">
                            {% for keys,valor in dades.aules.items() %}
                                <option id="{{valor.id}}" value={{valor.id}}>{{ keys }}</option>
                            {% endfor %}
                    </select>
                    <button onclick="remove_aula()" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Eliminar</button>
                    <br>
                </div>
            <h2 style="text-align:center;">Afegir interval</h2><hr>
                <div style="text-align:center;">
                    <select id="interval" style="text-align:center" class="selectpicker show-tick">
                        {% for hora in dades.intervals %}
                          <option value={{hora.key}}>{{ hora.value }}</option>
                        {% endfor %}
                    </select>
                    <select id="dia" class="selectpicker show-tick">
                    {% for dia in dies %}
                        <option value={{dia.key}}>{{dia.value}}</option>
                    {% endfor %}
                    </select>
                    <select  id="aula" style="text-align:center" class="selectpicker show-tick" data-show-subtext="true" data-live-search="true">
                        {% for keys,valor in dades.aules.items() %}
                            <option value={{keys}}>{{ keys }}</option>
                        {% endfor %}
                    </select>
                    <button onclick="new_rule()" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Afegir</button>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
            <h2 style="text-align:center;">Intervals definits</h2><hr>
            <table id="drops" name="drops" style="text-align:center" class="table table-striped" width="100%" cellspacing="0">
                <thead>
                    <tr >
                        <th></th>
                        <th style="text-align:center">Aula</th>
                        <th style="text-align:center">Ip</th>
                        <th style="text-align:center">Buidar aula</th>
                    </tr>
                </thead>
            </table>
        </div>
                
    </body>
</html>

gestio_aules/app/templates/pages/aula_desconeguda.html
<html>
    <head>
        <META charset="UTF-8">
        <TITLE>Internet</TITLE>
        <link href="/internet/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/internet/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="/internet/static/bower_components/pnotify/dist/js/pnotify.custom.min.js"></script>
        <link href="/internet/static/bower_components/pnotify/dist/css/pnotify.custom.min.css" rel="stylesheet">
        <style>

            .divcentre {
                position: absolute;
                top: 45%;
                left:50%;
                transform: translate(-50%,-50%);
            }
        </style>
        <script src="/internet/static/js/aula_desconeguda.js"></script>
    </head>
    <body>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="margin-top:2%">
            <ul class="nav navbar-nav navbar-right" style="margin-right:2%">
                <li>
                    <button class="btn btn-default btn-lg grey" data-toggle="dropdown" aria-expanded="false">
                        {{ user.name }}&nbsp;&nbsp;<i class="glyphicon glyphicon-th-list"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        {% if user.role == 'admin' %}
            			<li>
                            <a href="{{ url_for('bpAdmin.admin') }}"><i class="glyphicon glyphicon-star-empty"></i>&nbsp;&nbsp;Admin</a>
            			</li>
                        {% endif %}
                        <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>&nbsp;&nbsp;Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="row divcentre">
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="text-align:center;">
                <img src="/internet/static/css/img/ladybug.png" width="110px" height="95px">
            </div>
            <div class="col-sm-2 col-md-2 col-xs-2 col-lg-2">
            </div>
            <div class="col-sm-8 col-md-8 col-xs-8 col-lg-8 text-center">
                <h1>Et trobes en una aula desconeguda pel sistema.</h1><br>
                <h4>Per tal de poder controlar l'aula demaneu-ne l'activació:</h4>
                    <div class="input-group" style="margin:25px">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-pencil"></span></div>
                        <input id="aula" type="text" class="form-control" style="width: 100%" name="text" placeholder="Nom d'aula">
                    </div>
                    <button onclick="enviar_email()" id="boton_enviar" class="btn btn-success"><span class="glyphicon glyphicon-send"></span>&nbsp&nbspDemanar activació</button>
                    <br><br>
                </div>
            <div class="col-sm-2 col-md-2 col-xs-2 col-lg-2">
            </div>
        </div>
    </body>
</html>

gestio_aules/app/templates/pages/errorValidacio.html
<html>
    <head>
        <META charset="UTF-8">
        <TITLE>Internet</TITLE>
        <link href="/internet/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/internet/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <style>
            .divcentre {
                position: absolute;
                top: 45%;
                left:50%;
                transform: translate(-50%,-50%);
            }

            .rotate180 {
                -webkit-transform: rotate(180deg);
                -moz-transform: rotate(180deg);
                -o-transform: rotate(180deg);
                -ms-transform: rotate(180deg);
                transform: rotate(180deg);
            }

        </style>
    </head>
    <body>
        <div style="margin-top: 1%; margin-left: 1%">
            <a class="btn btn-default btn-lg grey" href="{{url_for('logout')}}">
                <i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>&nbsp;&nbsp;Log Out
            </a>
        </div>
        <div class="container" style="margin-top: 5%">
            <div class="jumbotron">
                <div class="container for-about text-center">
                     <h1>Error!</h1>
                     <p>Per veure aquesta pàgina s'ha de ser professor</p>
                     <img src="/internet/static/css/img/ladybug.png" class="rotate180" width="18%" height="15%">
                </div>
            </div>
            <div>
                <hr>
                <div class="row" style=" margin: 0 20px">
                    <div class="col-sm-2 col-md-2 col-xs-4 col-lg-3">
                    </div>
                        <div class="col-sm-8 col-md-8 col-xs-4 col-lg-6 text-center">
                        <!--
                                <p>info@isard.io</p>
                                <p><i>Licensed under GPL v3 license</i></p>
                        -->
                                <h3>Authors:</h3>
                                <b>Alberto Larraz Dalmases</b><br>
                                (alberto.larraz@gmail.com)<br>
                                <b>Josep Maria Viñolas Auquer</b><br>
                                (vinolasbcn@gmail.com)<br>
                                <b>Alex Miranda Gonzalez</b><br>
                                (amirandagon@gmail.com)<br>
                                <b>Miriam Melina Gamboa Valdez</b><br>
                                (melinav98@gmail.com)

                        </div>
                    <div class="col-sm-2 col-md-2 col-xs-4 col-lg-3">
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

gestio_aules/app/templates/pages/landing.html
<html>
    <head>
        <META charset="UTF-8">
        <TITLE>Internet</TITLE>
        <link href="/internet/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/internet/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <link href="/internet/static/bower_components/bootstrap-select-1.12.4/dist/css/bootstrap-select.min.css" rel="stylesheet">
        <script src="/internet/static/bower_components/bootstrap-select-1.12.4/dist/js/bootstrap-select.min.js"></script>
        <script src="/internet/static/bower_components/pnotify/dist/js/pnotify.custom.min.js"></script>
        <link href="/internet/static/bower_components/pnotify/dist/css/pnotify.custom.min.css" rel="stylesheet">
        <style>

            .hover-btn {
                display: none;
            }

            tr:hover .hover-btn {
                display: block;
            }

            td {
                width: 15%;
            }

            .grey {
                color:
            }

        </style>
        <script src="/internet/static/js/landing.js"></script>
    </head>
    <body>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="margin-top:2%">
            <ul class="nav navbar-nav navbar-right" style="margin-right:2%">
                <li>
                    <button class="btn btn-default btn-lg grey" data-toggle="dropdown" aria-expanded="false">
                        {{ user.name }}&nbsp;&nbsp;<i class="glyphicon glyphicon-th-list"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        {% if user.role == 'admin' %}
            			<li>
                            <a href="{{ url_for('bpAdmin.admin') }}"><i class="glyphicon glyphicon-star-empty"></i>&nbsp;&nbsp;Admin</a>
            			</li>
                        {% endif %}
                        <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>&nbsp;&nbsp;Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12" style="text-align:center; margin-top:5%">
            <img src="/internet/static/css/img/ladybug.png" width="110px" height="95px"><br><br>
        </div>
        <div class="row" style="margin: 0 20px">
            <h1 style="text-align:center;" >Gestió de {{ dades.aula }}</h1>
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                <h2 style="text-align:center;">Afegir interval</h2>
                <hr>
                    <select id="interval" style="text-align:center" class="selectpicker show-tick">
                        {% for hora in dades.intervals %}
                          <option value={{hora.key}}>{{ hora.value }}</option>
                        {% endfor %}
                    </select>
                    <br><br>
                    <select id="dia" class="selectpicker show-tick" data-width="75%">
                    {% for dia in dies %}
                        <option value={{dia.key}}>{{dia.value}}</option>
                    {% endfor %}
                    </select>
                    <br><br>
                    <button onclick="new_rule()" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Afegir</button><br><br>
                    <button onclick="remove_all()" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Eliminar tots els intervals</button>
            </div>
       <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
            <h2 style="text-align:center;">Intervals</h2>
            <hr>
            <table class="table table-striped" id="drops">
                <thead>
                    <tr>
                        <th>Dia</th>
                        <th>Interval</th>
                        <th></th>
                    </tr>
                </thead>
                {% for valor in dades.drops %}
                  <tr id="{{valor.id.split('*')[1]}}">
                    {% for dia in dies %}
                        {% if dia.key == valor.time.split(',')[1] %}
                            <td> {{ dia.value }} </td>
                        {% endif %}
                    {% endfor %}
                    <td>{{valor.time.split(',')[0]}}</td>
                    <td>
                        <div class="hover-btn">
                            <button onclick="remove_rule('{{valor.id}}')" style="text-align: center" class="btn btn-danger btn-sm">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </div>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
        </div>
    </body>
</html>